categories = [{'name': 'Academia',
               'types': ['library',
                         'school']},

              {'name': 'Food & Drink',
               'types': ['bakery',
                         'bar',
                         'cafe',
                         'meal_delivery',
                         'meal_takeaway',
                         'restaurant',
                         'supermarket']},

              {'name': 'Recreation',
               'types': ['amusement_park',
                         'aquarium',
                         'bowling_alley',
                         'campground',
                         'casino',
                         'zoo',
                         'park',
                         'movie_theater',
                         'night_club',
                         'shopping_mall',
                         'stadium',
                         'spa',
                         'museum',
                         'art_gallery']},

              {'name': 'Health',
               'types': ['dentist',
                         'doctor',
                         'hospital',
                         'physiotherapist']},

              {'name': 'Shopping',
               'types': ['bicycle_store',
                         'book_store',
                         'furniture_store',
                         'hardware_store',
                         'home_goods_store',
                         'shoe_store',
                         'store',
                         'clothing_store']},

              {'name': 'Religion',
               'types': ['cemetery',
                         'church',
                         'hindu_temple',
                         'mosque',
                         'synagogue']}
              ]
